version: '3.8'

services:
  postgres:
    image: postgres:alpine:3.22
    container_name: cicero-postgres-db
    enviroments:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes: 
      - cicero-postgres-data:/var/lib/postgresql/data

volumes:
  cicero-postgres-data:
    driver: local